### ISSUE TITLE
[menu] allow customizing the column count of dropdown menus

### ISSUE THREAD

**Issue by razonyang** [hbstack/header#309]

**Comment by TetraTheta** [comment]
I'm cross-posting my opinion here, from #308. Since this issue is dedicated for the suggestion I've put at #308, I think this is better place for discussing about it.

---

> Actually, it will be limited max to 2 if implemented (that is, the columns range is 1-2), since there aren't enough space for more columns, otherwise the rest columns will overflow and be hidden. Beside this behavior affects desktop screen only.
> 
> In this point, it seems that no neccessary to have this option, unless you want to display one column on desktop all the time.

If then, we can have the option named `one-column` as boolean type which its default value is `false` for simplicity.

This would be niche use case anyway though.

> I want to display 'A' menu as one column, but also want to display 'B' menu as two column because child menu of 'B' is too many for one column.
> 
> The 'A' menu also have some child menu, but I prefer display it as one column anyway.

In this case, if we don't have such option, displaying two type at once isn't possible. Site owner must choose either one column or two columns for all menus. 

I'm not sure if enforcing it would be good idea or not. Of course, displaying child menu items as two columns would have better visibility.

```
@include media-breakpoint-up($hb-header-breakpoint) {
    .hb-header-submenus {
      column-count: 2;
    }

    .hb-header-submenu {
      max-width: 35vw;
      overflow: hidden;
    }
}
```
These lines were added in a3c2ffcaa25434c4fa5644a2311ab0db55ee3d06 but I wonder if it is possible to apply or remove this rule selectively to certain menus.

**Comment by razonyang** [comment]
Now the columns will be `1` by default, when the number of sub menus is greater or equal 6, then it will be `2` by default.
You can also tweak it via the `columns` parameter of menus.

BTW, as I described before, it's limited up to `2`, if you find a solution to make it suit any column count, PR are welcome.

**Comment by TetraTheta** [comment]
Thank you for the fast improvement!

I don't have any objection about limiting column count to 2.

In my opinion, if a menu has lots of sub-menus that exceeds `100vh` when displayed with two column, site owner should think about displaying menus in sidebar, rather than top.
